
spring:
  application:
    name: eureka
server:
  port: 9000
eureka:
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 100000
  client:
    register-with-eureka: false
    fetch-registry: false
debug: true
